# ===== DATASOURCE =====
quarkus.datasource.db-kind=sqlite

quarkus.datasource.jdbc.url=jdbc:sqlite:local-dev.db

quarkus.devservices.enabled=false

# ===== HIBERNATE =====
quarkus.hibernate-orm.database.generation=validate
# quarkus.hibernate-orm.log.sql=true

# ===== LIQUIBASE =====
quarkus.liquibase.migrate-at-start=true
quarkus.liquibase.change-log=db/changelog/db.changelog-master.yaml